Repository OhHapJiJol/YoRiJoRi-api, pull requests merged in 2021-04, with the labels that each got.

#13 YORIJORI-15 테스트
  src/main/resources/static/.gitignore
Labels: documentation

#14 YORIJORI-17 Dockerfile Unable Access Bug fix
  Dockerfile
Labels: bug, feature

#15 YORIJORI-16 테스트
  src/main/resources/static/.gitignore
Labels: documentation

#16 [YORIJORI-10] 메뉴 카테고리 테이블
  build.gradle
  src/main/java/dev/ohjj/yorijori/api/controller/MenuController.java
  src/main/java/dev/ohjj/yorijori/api/controller/request/MenuRequest.java
  src/main/java/dev/ohjj/yorijori/api/menu/category/MenuCategoryService.java
  src/main/java/dev/ohjj/yorijori/api/menu/category/model/MenuCategory.java
  src/main/java/dev/ohjj/yorijori/api/persistence/menu/entity/MenuCategoryEntity.java
  src/main/java/dev/ohjj/yorijori/api/persistence/menu/repository/MenuCategoryRepository.java
  src/main/java/dev/ohjj/yorijori/rest/MenuController.http
  src/main/java/dev/ohjj/yorijori/rest/http-client.env.json
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
  src/test/java/dev/ohjj/yorijori/api/persistence/menu/repository/MenuCategoryRepositoryTest.java
Labels: feature

#19 [YORIJORI-9] 메뉴 테이블 설계
  src/main/java/dev/ohjj/yorijori/api/controller/MenuController.java
  src/main/java/dev/ohjj/yorijori/api/controller/request/MenuRequest.java
  src/main/java/dev/ohjj/yorijori/api/menu/MenuService.java
  src/main/java/dev/ohjj/yorijori/api/menu/category/model/MenuCategory.java
  src/main/java/dev/ohjj/yorijori/api/menu/model/Menu.java
  src/main/java/dev/ohjj/yorijori/api/persistence/menu/entity/MenuCategoryEntity.java
  src/main/java/dev/ohjj/yorijori/api/persistence/menu/entity/MenuEntity.java
  src/main/java/dev/ohjj/yorijori/api/persistence/menu/repository/MenuRepository.java
  src/main/java/dev/ohjj/yorijori/rest/MenuController.http
  src/test/java/dev/ohjj/yorijori/api/persistence/menu/repository/MenuRepositoryTest.java
Labels: feature
